Fixed publisher list in harvester
surfedushare/search-portal pull request #326
Opened 2020-11-30 15:02 UTC by kiruys

First I noticed that the fixture was broken with respect to the publisher field. I have made sure that the structure of the publisher field is equal to the data dump json.
Then, I added a test for the publisher field and fixed the parser.

2020-11-30 15:22 UTC, Ruben-Hartog reviewed
Yes, nice! Is het misschien handig om toch https://github.com/eventable/vobject te gebruiken ipv die parse_vcard? Als ik die specificatie lees zou het goed kunnen dat er nog wel meer vreemde dingen in voor komen.. Die package parsed het gewoon voor ons 😄

2020-12-01 08:20 UTC, Ruben-Hartog approved these changes

2020-12-01 08:36 UTC, fako requested changes
Ik denk dat de oplossing in de parse_vcard moet plaatsvinden of de parse vcard moet vervangen worden met die van de package (en dat lost ook problemen met komma's op).

Als we parse_vcard fixen/vervangen dan fixen we namelijk ook direct author, want die gebruikt dezelfde functie.

2020-12-01 08:36 UTC, fako commented on harvester/edurep/tests/utils.py
> +        self.assertEqual(seeds[3]['publishers'], ['AERES Hogeschool', 'HAS Hogeschool', 'Van Hall Larenstein'])
Volgens mij zou de output moeten zijn: "AERES Hogeschool; HAS Hogeschool; Van Hall Larenstein". 
Het zijn geen individuele publishers. Ze publishen het samen als een enkele publisher en ze gebruiken ; als scheidingsteken.

2020-12-01 11:16 UTC, fako approved these changes
Awesome!

2020-12-01 12:13 UTC, merged