Pre filters responsive
surfedushare/search-portal pull request #645
Opened 2022-02-28 13:31 UTC by naftalivanderloon

2022-02-28 15:42 UTC, fako requested changes

2022-02-28 15:42 UTC, fako commented on portal/src/components/FilterCategories/FilterDropdown.vue
> +      <div class="dropdown-container__selector" :class="{ 'active': visible == true }"></div>
=== gebruiken om implicit type matching te voorkomen?

2022-02-28 15:42 UTC, fako commented on portal/src/components/FilterCategories/FilterDropdown.vue
> +      :data-test="'filter_' + field"
Deze property misschien data-filter-field noemen, want hoewel het in de tests gebruikt kan worden is het niet perse iets voor alleen de tests.

2022-02-28 15:42 UTC, fako commented on portal/src/components/FilterCategories/FilterDropdown.vue
> +            :data-test="'filter_' + field + '_' + filter.external_id"
Zelfde punt qua attribute naming

2022-02-28 15:42 UTC, fako commented on portal/src/components/MainHeader/MainHeader.component.less
> +    @media @mobile-ls {
Waar staat ls voor?

2022-02-28 15:42 UTC, fako commented on portal/src/components/Search/PreSearchFilters.vue
> +  <div class="presearchfilters" v-if="dropdownData" tabindex="-1" @focusout="onFocusOut">
Even runnen en committen om de warnings hieronder te fixen:
npm run lint -- --fix

2022-02-28 15:42 UTC, fako commented on portal/src/components/Search/SearchTerm.vue
> +        placeholder: this.placeholder || this.$t('title-author-subject'),
Kun je dit gelijk even op prod database zetten? Zal ik bij deploy naar acceptance kopietje maken van prod database en staat het direct goed voor de release.

2022-02-28 15:42 UTC, fako commented on portal/src/variables.less
> +##Device = Tablets, Ipads (landscape)
Aha, ls staat voor landscape, never mind :)

2022-02-28 15:42 UTC, fako commented on service/e2e_tests/test_search.py
> +        self.selenium.get(self.live_server_url + "?demo=true")
Did nog even niet committen dan? Zat in de andere PR, die we gesloten hebben.

2022-02-28 15:42 UTC, fako commented on service/e2e_tests/test_search.py
> -        self.skipTest("Skipped due to strange Github behaviour")
Dit moet je ook niet committen. Heb dit ooit gecommit en toen gingen de tests weer vaker mis. Toen heb ik het gerevert. Niet helemaal duidelijk waarom jij het nu weer opneemt. Ik vermoed per ongeluk, dus lijkt mij dat we dit niet moeten mergen. Laat het weten als je er anders over denkt.

2022-02-28 16:48 UTC, naftalivanderloon commented on portal/src/components/FilterCategories/FilterDropdown.vue
> +      :data-test="'filter_' + field"
zie [Cypress best practices](https://docs.cypress.io/guides/references/best-practices#Selecting-Elements)

2022-02-28 17:12 UTC, naftalivanderloon commented on portal/src/components/Search/SearchTerm.vue
> +        placeholder: this.placeholder || this.$t('title-author-subject'),
ik mag dit nog steeds niet

2022-03-01 08:54 UTC, fako commented on portal/src/components/Search/SearchTerm.vue
> +        placeholder: this.placeholder || this.$t('title-author-subject'),
Zucht is ook zo. Zit eraan te komen ...

2022-03-01 08:55 UTC, merged